version: "3.9"
services:
  web:
    environment:
      - PG_DBNAME=sam
      - PG_USER=sam
      - PG_PASS=xxx
      - PG_ADDRESS=xxx
    build: .
    ports:
      - "8000:8000"
    expose:
      - "8000"
  rust:
    image: "rust:latest"
    